import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  countryCodes: [
    { code: "+355", name: "Albanie" },
    { code: "+213", name: "Algérie" },
    { code: "+376", name: "Andorre" },
    { code: "+54", name: "Argentine" },
    { code: "+374", name: "Arménie" },
    { code: "+297", name: "Aruba" },
    { code: "+61", name: "Australie" },
    { code: "+43", name: "Autriche" },
    { code: "+994", name: "Azerbaïdjan" },
    { code: "+1 268", name: "Antigua-et-Barbuda" },
    { code: "+1 242", name: "Bahamas" },
    { code: "+973", name: "Bahreïn" },
    { code: "+880", name: "Bangladesh" },
    { code: "+1 246", name: "Barbade" },
    { code: "+375", name: "Biélorussie" },
    { code: "+32", name: "Belgique" },
    { code: "+501", name: "Belize" },
    { code: "+229", name: "Bénin" },
    { code: "+975", name: "Bhoutan" },
    { code: "+591", name: "Bolivie" },
    { code: "+387", name: "Bosnie-Herzégovine" },
    { code: "+267", name: "Botswana" },
    { code: "+55", name: "Brésil" },
    { code: "+673", name: "Brunei" },
    { code: "+359", name: "Bulgarie" },
    { code: "+226", name: "Burkina Faso" },
    { code: "+257", name: "Burundi" },
    { code: "+855", name: "Cambodge" },
    { code: "+237", name: "Cameroun" },
    { code: "+1", name: "Canada" },
    { code: "+238", name: "Cap-Vert" },
    { code: "+236", name: "République centrafricaine" },
    { code: "+235", name: "Tchad" },
    { code: "+56", name: "Chili" },
    { code: "+86", name: "Chine" },
    { code: "+357", name: "Chypre" },
    { code: "+57", name: "Colombie" },
    { code: "+269", name: "Comores" },
    { code: "+506", name: "Costa Rica" },
    { code: "+385", name: "Croatie" },
    { code: "+53", name: "Cuba" },
    { code: "+599", name: "Curaçao" },
    { code: "+45", name: "Danemark" },
    { code: "+253", name: "Djibouti" },
    { code: "+1 767", name: "Dominique" },
    { code: "+1", name: "République dominicaine" },
    { code: "+670", name: "Timor oriental" },
    { code: "+593", name: "Équateur" },
    { code: "+20", name: "Égypte" },
    { code: "+503", name: "Salvador" },
    { code: "+291", name: "Érythrée" },
    { code: "+372", name: "Estonie" },
    { code: "+251", name: "Éthiopie" },
    { code: "+679", name: "Fidji" },
    { code: "+358", name: "Finlande" },
    { code: "+33", name: "France" },
    { code: "+241", name: "Gabon" },
    { code: "+220", name: "Gambie" },
    { code: "+995", name: "Géorgie" },
    { code: "+49", name: "Allemagne" },
    { code: "+233", name: "Ghana" },
    { code: "+350", name: "Gibraltar" },
    { code: "+30", name: "Grèce" },
    { code: "+299", name: "Groenland" },
    { code: "+1 473", name: "Grenade" },
    { code: "+502", name: "Guatemala" },
    { code: "+224", name: "Guinée" },
    { code: "+245", name: "Guinée-Bissau" },
    { code: "+592", name: "Guyana" },
    { code: "+509", name: "Haïti" },
    { code: "+504", name: "Honduras" },
    { code: "+852", name: "Hong Kong" },
    { code: "+36", name: "Hongrie" },
    { code: "+354", name: "Islande" },
    { code: "+91", name: "Inde" },
    { code: "+62", name: "Indonésie" },
    { code: "+98", name: "Iran" },
    { code: "+964", name: "Irak" },
    { code: "+353", name: "Irlande" },
    { code: "+44", name: "Royaume-Uni" },
    { code: "+972", name: "Israël" },
    { code: "+39", name: "Italie" },
    { code: "+225", name: "Côte d'Ivoire" },
    { code: "+1 876", name: "Jamaïque" },
    { code: "+81", name: "Japon" },
    { code: "+962", name: "Jordanie" },
    { code: "+7", name: "Kazakhstan" },
    { code: "+254", name: "Kenya" },
    { code: "+686", name: "Kiribati" },
    { code: "+965", name: "Koweït" },
    { code: "+996", name: "Kirghizistan" },
    { code: "+856", name: "Laos" },
    { code: "+371", name: "Lettonie" },
    { code: "+961", name: "Liban" },
    { code: "+266", name: "Lesotho" },
    { code: "+231", name: "Liberia" },
    { code: "+218", name: "Libye" },
    { code: "+423", name: "Liechtenstein" },
    { code: "+370", name: "Lituanie" },
    { code: "+352", name: "Luxembourg" },
    { code: "+853", name: "Macao" },
    { code: "+389", name: "Macédoine du Nord" },
    { code: "+261", name: "Madagascar" },
    { code: "+265", name: "Malawi" },
    { code: "+60", name: "Malaisie" },
    { code: "+960", name: "Maldives" },
    { code: "+223", name: "Mali" },
    { code: "+356", name: "Malte" },
    { code: "+692", name: "Îles Marshall" },
    { code: "+222", name: "Mauritanie" },
    { code: "+230", name: "Maurice" },
    { code: "+262", name: "Mayotte" },
    { code: "+52", name: "Mexique" },
    { code: "+691", name: "États fédérés de Micronésie" },
    { code: "+373", name: "Moldavie" },
    { code: "+377", name: "Monaco" },
    { code: "+976", name: "Mongolie" },
    { code: "+382", name: "Monténégro" },
    { code: "+212", name: "Maroc" },
    { code: "+258", name: "Mozambique" },
    { code: "+264", name: "Namibie" },
    { code: "+674", name: "Nauru" },
    { code: "+977", name: "Népal" },
    { code: "+31", name: "Pays-Bas" },
    { code: "+687", name: "Nouvelle-Calédonie" },
    { code: "+64", name: "Nouvelle-Zélande" },
    { code: "+505", name: "Nicaragua" },
    { code: "+227", name: "Niger" },
    { code: "+234", name: "Nigeria" },
    { code: "+683", name: "Niue" },
    { code: "+47", name: "Norvège" },
    { code: "+968", name: "Oman" },
    { code: "+92", name: "Pakistan" },
    { code: "+680", name: "Palaos" },
    { code: "+970", name: "Palestine" },
    { code: "+507", name: "Panama" },
    { code: "+675", name: "Papouasie-Nouvelle-Guinée" },
    { code: "+595", name: "Paraguay" },
    { code: "+51", name: "Pérou" },
    { code: "+63", name: "Philippines" },
    { code: "+48", name: "Pologne" },
    { code: "+351", name: "Portugal" },
    { code: "+1 787", name: "Porto Rico" },
    { code: "+974", name: "Qatar" },
    { code: "+262", name: "Réunion" },
    { code: "+40", name: "Roumanie" },
    { code: "+7", name: "Russie" },
    { code: "+250", name: "Rwanda" },
    { code: "+590", name: "Guadeloupe" },
    { code: "+509", name: "Haïti" },
    { code: "+685", name: "Samoa" },
    { code: "+378", name: "Saint-Marin" },
    { code: "+239", name: "Sao Tomé-et-Principe" },
    { code: "+966", name: "Arabie Saoudite" },
    { code: "+221", name: "Sénégal" },
    { code: "+381", name: "Serbie" },
    { code: "+248", name: "Seychelles" },
    { code: "+232", name: "Sierra Leone" },
    { code: "+65", name: "Singapour" },
    { code: "+421", name: "Slovaquie" },
    { code: "+386", name: "Slovénie" },
    { code: "+677", name: "Solomons" },
    { code: "+27", name: "Afrique du Sud" },
    { code: "+34", name: "Espagne" },
    { code: "+94", name: "Sri Lanka" },
    { code: "+249", name: "Soudan" },
    { code: "+597", name: "Suriname" },
    { code: "+268", name: "Swaziland" },
    { code: "+46", name: "Suède" },
    { code: "+41", name: "Suisse" },
    { code: "+963", name: "Syrie" },
    { code: "+886", name: "Taïwan" },
    { code: "+992", name: "Tadjikistan" },
    { code: "+255", name: "Tanzanie" },
    { code: "+66", name: "Thaïlande" },
    { code: "+228", name: "Togo" },
    { code: "+676", name: "Tonga" },
    { code: "+1 868", name: "Trinité-et-Tobago" },
    { code: "+216", name: "Tunisie" },
    { code: "+90", name: "Turquie" },
    { code: "+993", name: "Turkménistan" },
    { code: "+1 649", name: "Îles Turques-et-Caïques" },
    { code: "+688", name: "Tuvalu" },
    { code: "+256", name: "Ouganda" },
    { code: "+380", name: "Ukraine" },
    { code: "+971", name: "Émirats Arabes Unis" },
    { code: "+44", name: "Royaume-Uni" },
    { code: "+1", name: "États-Unis" },
    { code: "+598", name: "Uruguay" },
    { code: "+998", name: "Ouzbékistan" },
    { code: "+678", name: "Vanuatu" },
    { code: "+58", name: "Venezuela" },
    { code: "+84", name: "Vietnam" },
    { code: "+967", name: "Yémen" },
    { code: "+260", name: "Zambie" },
    { code: "+263", name: "Zimbabwe" }
  ]
};

const countryCodesSlice = createSlice({
  name: 'countryCodes',
  initialState,
  reducers: {}
});

export const selectCountryCodes = (state) => state.countryCodes.countryCodes;

export default countryCodesSlice.reducer;
