import * as React from 'react';
import Card from '@mui/joy/Card';
import Typography from '@mui/joy/Typography';
import Input from '@mui/joy/Input';
import Button from '@mui/joy/Button';

export default function Step3() {
  return (
    <Card
      size="lg"
      variant="plain"
      sx={{
        textAlign: 'left',
        maxWidth: '100%',
        width: 500,
        padding: 2,
      }}
    >
      <Typography level="title-lg" fontWeight="lg" mb={1}>
        3. Enter your Authentication Code
      </Typography>
      <Typography fontSize="sm" sx={{ mb: 2 }}>
        Enter the 6-digit code generated by your authenticator app:
      </Typography>
      <Input
        placeholder="Enter 6-digit code"
        sx={{ mb: 2 }}
      />
      <Button
        variant="solid"
        color="primary"
        sx={{
          width: '100%',
          borderRadius: 10,
          mb: 2,
        }}
      >
        Verify and Continue
      </Button>
      <Button
        variant="outlined"
        color="neutral"
        sx={{
          width: '100%',
          borderRadius: 10,
        }}
      >
        Authenticate via SMS
      </Button>
    </Card>
  );
}
