import * as React from 'react';
import AspectRatio from '@mui/joy/AspectRatio';
import Button from '@mui/joy/Button';
import Card from '@mui/joy/Card';
import Typography from '@mui/joy/Typography';
import Input from '@mui/joy/Input';

export default function Step1() {
  return (
    <Card
      size="lg"
      variant="plain"
      orientation="vertical"
      sx={{
        textAlign: 'left',
        maxWidth: '100%',
        width: 500,
        padding: 3,
        boxShadow: 1,
        borderRadius: 2,
      }}
    >
      <Typography fontSize="xl2" fontWeight="xl" mb={3}>
        Set Up Your Authenticator
      </Typography>

      <Typography level="title-lg" fontWeight="lg" mb={2}>
        1. Download an Authenticator App
      </Typography>
      <Typography fontSize="sm" sx={{ mb: 2 }}>
        Install an authenticator app like <strong>Google Authenticator</strong>, <strong>Authy</strong>, <strong>Duo Mobile</strong>, or <strong>1Password</strong>. If you'd rather not use an app, you can authenticate via SMS instead.
      </Typography>

      <Typography level="title-lg" fontWeight="lg" mb={2}>
        2. Scan the Barcode
      </Typography>

      <Typography fontSize="sm" sx={{ mb: 2 }}>
        If you are unable to scan this barcode, manually enter the following code:
      </Typography>
      <Typography fontSize="md" fontWeight="md" sx={{ mb: 2 }}>
        <code>1234 ABCD 4567 DEFG</code>
      </Typography>

      <Typography level="title-lg" fontWeight="lg" mb={2}>
        3. Enter Your Authentication Code
      </Typography>
      <Typography fontSize="sm" sx={{ mb: 2 }}>
        Enter the 6-digit code generated by your authenticator app:
      </Typography>
      <Input
        placeholder="Enter 6-digit code"
        sx={{ mb: 3 }}
      />

      <Button
        variant="solid"
        color="primary"
        sx={{
          width: '100%',
          borderRadius: 10,
          mb: 1,
        }}
      >
        Verify and Continue
      </Button>
    </Card>
  );
}
